Enable artwork
solowresidual/podcast-database pull request #83
Opened 2020-11-26 16:36 UTC by b-lauren

Closes #62 

Enabled artwork

2020-11-26 16:50 UTC, solowresidual approved these changes
Looks good nice work! Does Episode need to be able to hand a photo, too?

2020-11-26 16:53 UTC, b-lauren commented
@solowresidual episode image will just be the podcast artwork, right? Can add it though!

2020-11-26 17:00 UTC, johnjoubert requested changes

2020-11-26 17:02 UTC, johnjoubert commented on .gitignore
> +.env*
We can also remove this one actually because it's already on line 38.
```suggestion
```

2020-11-26 18:11 UTC, b-lauren commented
@johnjoubert sorted!

2020-11-27 11:27 UTC, johnjoubert approved these changes

2020-11-27 11:28 UTC, solowresidual approved these changes

2020-11-27 11:28 UTC, merged